In [1]:
# import all modules here
# please rerun the cell after adding new imports
import torch
from torch import tensor
from torch import nn
import numpy as np
import pandas as pd

In [2]:
torch.__version__

'2.1.2+cu121'

Scalar it has only value no direction
ezxample numbers like 43, 694
and has no dimensions

In [3]:
scalar = torch.tensor(43)
scalar

tensor(43)

In [4]:
type(scalar)

torch.Tensor

In [5]:
scalar.ndim

0

In [6]:
scalar.item()

43

# Vector
Contains values plus direction
array can be considered as vector


In [7]:
vector = tensor([34,56])

In [8]:
print(vector.dtype)
print(vector.size())
print(vector.shape)
print(vector.ndim)
print(vector)

torch.int64
torch.Size([2])
torch.Size([2])
1
tensor([34, 56])


# Matrix

In [9]:
matrix = tensor([
    [1,2],
    [3,4],
], dtype=torch.float)

In [10]:
matrix.dtype

torch.float32

In [11]:
matrix.shape

torch.Size([2, 2])

In [12]:
matrix.ndim

2

In [13]:
Tensor = tensor([
    [[
        1,2
    ]]
])

In [14]:
Tensor.ndim

3

In [15]:
Tensor.shape

torch.Size([1, 1, 2])

In [16]:
Tensor[:, :, :]

tensor([[[1, 2]]])

# Random Tensor

In [17]:
random_tensor = torch.rand(size=[2,3])

In [18]:
random_tensor[:, 2]

tensor([0.9329, 0.0273])

In [19]:
random_tensor.dtype

torch.float32

In [20]:
zeros_tensor = torch.zeros(size=[2,3])

In [21]:
zeros_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [22]:
ones_tensor = torch.ones(size=[2,3])

In [23]:
ones_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [24]:
zero_to_ten = torch.range(0, 10)

/tmp/ipykernel_38622/317937602.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten = torch.range(0, 10)


In [25]:
zero_to_ten

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [26]:
zero_to_ten_arange = torch.arange(0, 10, 2)

In [27]:
zero_to_ten_arange

tensor([0, 2, 4, 6, 8])

In [28]:
torch.cuda.is_available()

True

In [29]:
float_32_tensor = torch.tensor(
    [3.4, 4, 6],
    dtype=torch.float,
    device='cuda:0',
    requires_grad=False
                              )

In [30]:
float_32_tensor

tensor([3.4000, 4.0000, 6.0000], device='cuda:0')

In [31]:
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cuda', index=0))

In [32]:
basic_tensor = tensor([1,2,3])

In [33]:
basic_tensor ** 3

tensor([ 1,  8, 27])

In [34]:
basic_tensor - 10
basic_tensor / 10
basic_tensor + 10

tensor([11, 12, 13])

In [35]:
torch.multiply(basic_tensor, 10)

tensor([10, 20, 30])

In [36]:
basic_tensor * basic_tensor

tensor([1, 4, 9])

In [37]:
torch.matmul(basic_tensor, basic_tensor)

tensor(14)

In [38]:
basic_tensor.shape

torch.Size([3])

In [39]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B.T) # (this will error)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [40]:
tensor_B.T

tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])

In [41]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [42]:
# torch.manual_seed(42)
# linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input 
#                          out_features=6) # out_features = describes outer value 
# x = tensor_A
# print(list(linear.parameters()))
# output = linear(x)
# print(f"Input shape: {x.shape}\n")
# print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

In [43]:
linear_nn = nn.Linear(in_features=2, out_features=6)
print(linear_nn.parameters())
logics = linear_nn(tensor_A)
print(logics)

<generator object Module.parameters at 0x7f32f5e99620>
tensor([[ 1.5579e+00, -1.2908e+00,  1.2290e-04,  9.3897e-01,  9.1430e-01,
          1.8929e+00],
        [ 2.5375e+00, -3.5429e+00, -1.0734e-01,  1.9560e+00,  2.4602e+00,
          3.4709e+00],
        [ 3.5171e+00, -5.7950e+00, -2.1481e-01,  2.9731e+00,  4.0060e+00,
          5.0490e+00]], grad_fn=<AddmmBackward0>)


In [44]:
tens = torch.arange(0, 101, 10)

In [45]:
tens.type(torch.float32).mean()
tens.type(torch.float32).sum()

tensor(550.)

In [46]:
tens.argmax()
tens.argmin().item()

0

### Reshaping, stacking, squeezing and unsqueezing


In [47]:
x = torch.arange(1,8)

In [48]:
x

tensor([1, 2, 3, 4, 5, 6, 7])

In [49]:
x.shape

torch.Size([7])

In [50]:
x.reshape(1,7)

tensor([[1, 2, 3, 4, 5, 6, 7]])

In [51]:
y = x.view(1,7)

In [52]:
y

tensor([[1, 2, 3, 4, 5, 6, 7]])

In [53]:
y[: ,5] = 11

In [54]:
y

tensor([[ 1,  2,  3,  4,  5, 11,  7]])

In [55]:
x

tensor([ 1,  2,  3,  4,  5, 11,  7])

In [56]:
y[0][5] = 6

In [57]:
y

tensor([[1, 2, 3, 4, 5, 6, 7]])

In [58]:
x_stacked = torch.stack([x,x,x,x], dim = 0)

In [59]:
x_stacked


tensor([[1, 2, 3, 4, 5, 6, 7],
        [1, 2, 3, 4, 5, 6, 7],
        [1, 2, 3, 4, 5, 6, 7],
        [1, 2, 3, 4, 5, 6, 7]])

In [60]:
y.unsqueeze(dim=2)

tensor([[[1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7]]])

In [61]:
def print_details(tens):
    print(tens.shape)
    print(tens.dtype)    
    print(tens.ndim)    
    

## PyTorch tensors & NumPy


In [62]:
arr = np.arange(1, 11)

In [63]:
arr


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
arr_tensor = tensor(arr, dtype=torch.float)
arr_tensor



tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [65]:
print_details(arr_tensor)

torch.Size([10])
torch.float32
1


In [66]:
from transformers import AutoTokenizer, AutoModelForCausalLM


In [69]:
import torch
torch.manual_seed(42)
# Create two random tensors
random_tensor_A = torch.rand(3, 4)
torch.manual_seed(42)

random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor B:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [71]:
!nvidia-smi

Wed Feb 21 22:46:06 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.40.07              Driver Version: 551.52         CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3080        On  |   00000000:01:00.0  On |                  N/A |
|  0%   54C    P8             35W /  320W |    2490MiB /  10240MiB |      8%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [72]:
torch.cuda.device_count()


1

In [80]:
tensor = torch.tensor([1,2.4, 5.], device='cuda')

In [82]:
tensor.device, tensor
from torch import tensor

In [83]:
tensor

<function torch._VariableFunctionsClass.tensor>

In [84]:
tensor_on_gpu = torch.rand([3,4], device ='cuda', dtype=torch.float)

In [86]:
tensor_on_gpu, tensor_on_gpu.device

(tensor([[0.6130, 0.0101, 0.3984, 0.0403],
         [0.1563, 0.4825, 0.7362, 0.4060],
         [0.5189, 0.2867, 0.2416, 0.9228]], device='cuda:0'),
 device(type='cuda', index=0))

In [87]:
tensor_on_cpu = torch.zeros(2,2)

In [88]:
tensor_on_cpu.numpy()

array([[0., 0.],
       [0., 0.]], dtype=float32)

In [91]:
tensor_on_gpu.type(torch.float64).cpu().numpy()

array([[0.61295986, 0.01005884, 0.39841369, 0.0403084 ],
       [0.15626675, 0.48247308, 0.7362473 , 0.40598196],
       [0.51889962, 0.2867111 , 0.24158043, 0.92283922]])